export const ACCESS_TOKEN = 'access_token'
export const REFRESH_TOKEN = 'refresh_token'
export const IS_LOGGING = 'is_logging'
export const USER_INFO = 'user'
export const CART_CHECKOUT = 'cart_checkout'
export const SEARCH_HISTORY = 'search_history'
