export const HOME_PATH = '/' as const
export const LOGIN_PATH = '/login'
export const REGISTER_PATH = '/register'
export const CART_PATH = '/cart'
export const CHECKOUT_PATH = '/checkout'
export const CHECKOUT_SUCCESS_PATH = '/checkout-success'
export const SEARCH_PATH = '/search'
export const USER_PATH = '/user'
export const USER_PATTERN = /^\/user(\/account)?$/
export const USER_PURCHASE_PATH = `${USER_PATH}/purchase`
export const USER_ACCOUNT_PATH = `${USER_PATH}/account`
export const USER_PROFILE_PATH = `${USER_ACCOUNT_PATH}/profile`
export const USER_ADDRESS_PATH = `${USER_ACCOUNT_PATH}/address`
export const USER_PASSWORD_PATH = `${USER_ACCOUNT_PATH}/password`
export const CATEGORY_PATH = '/:categorySlug'
export const PRODUCT_DETAIL_PATH = '/:categorySlug/:productSlug'
export const NOT_FOUND_PATH = '/not-found'
export const CATCH_ALL_PATH = '*'
